apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  replicas: 2                      # 2 copies de l'app en permanence
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: nastry69/todo-api:latest   # image poussée par le collègue en phase 3
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "todo_db"
            - name: DB_USER
              value: "todo_user"
            - name: DB_PASSWORD
              value: "todo_pass"
            - name: NODE_ENV
              value: "production"