name: CI - Todo API

on:
  push:
    branches: ["main", "feat/**"]
  pull_request:
    branches: ["main"]

jobs:

  # ── PHASE 1 : Tests unitaires (sans base de données) 
  test-unit:
    name: Tests unitaires
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les tests unitaires
        run: npm test
